name: Release

on:
  push: 
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle Environment
        uses: gradle/actions/setup-gradle@v4

      - name: BuildApk
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease

      - name: Publish Release
        uses: actions/upload-artifact@v3
        with:
          name: TimTool
          path: app/build/outputs/apk/release/*.apk
